<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RND-BASE-A" ignored="0" name="Default test" tests="128" failures="8" timestamp="2022-12-12T02:09:00 PST" time="91.441" errors="0">
  <testcase name="elascticsearchcreateindex_v_2" time="5.161" classname="Public.searchController"/>
  <testcase name="getAccountsAdvanced_v_2" time="0.012" classname="Public.searchController">
    <failure type="java.lang.AssertionError" message="Bug Reported">
      <![CDATA[java.lang.AssertionError: Bug Reported
at org.testng.Assert.fail(Assert.java:99)
at Public.searchController.getAccountsAdvanced_v_2(searchController.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getAccountsAdvanced_v_2 -->
  <testcase name="getAccounts_v_2" time="0.005" classname="Public.searchController">
    <failure type="java.lang.AssertionError" message="Bug Reported">
      <![CDATA[java.lang.AssertionError: Bug Reported
at org.testng.Assert.fail(Assert.java:99)
at Public.searchController.getAccounts_v_2(searchController.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getAccounts_v_2 -->
  <testcase name="getCustomer_v2" time="0.808" classname="Public.searchController"/>
  <testcase name="getindex_v2" time="0.6" classname="Public.searchController"/>
  <testcase name="getconsumptionHistoryController" time="0.748" classname="Public.consumptionHistoryControllerV3"/>
  <testcase name="getlocationsByCustomerv_2_4" time="0.835" classname="Public.customerController_v2_4"/>
  <testcase name="TC001_saveReciept" time="8.636" classname="Public.CashieringPostV3"/>
  <testcase name="TC002_RecieptAdjustment" time="0.46" classname="Public.CashieringPostV3"/>
  <testcase name="getdeposit_v_3" time="0.431" classname="Private.DepositsControllerV3"/>
  <testcase name="getdepositpaymentPlan_v_3" time="0.421" classname="Private.DepositsControllerV3"/>
  <testcase name="lookupDepositId_v_3" time="0.89" classname="Private.DepositsControllerV3"/>
  <testcase name="getconsumptionHistoryController" time="0.494" classname="Public.consumptionHistoryController"/>
  <testcase name="TC003_getCashin" time="0.883" classname="Public.CashieringGetV3"/>
  <testcase name="TC004_balances" time="1.112" classname="Public.CashieringGetV3"/>
  <testcase name="TC003_getnextReceipt" time="0.48" classname="Public.CashieringGetV3"/>
  <testcase name="TC004_getReceipt" time="1.196" classname="Public.CashieringGetV3"/>
  <testcase name="TC005_getRegisterInfo" time="0.516" classname="Public.CashieringGetV3"/>
  <testcase name="TC006_gettransactions" time="1.157" classname="Public.CashieringGetV3"/>
  <testcase name="TC007_getAutoApply" time="1.303" classname="Public.CashieringGetV3"/>
  <testcase name="getdepositpaymentPlan_v_3" time="0.362" classname="Public.TestAPI"/>
  <testcase name="postsmartlistfavorite_v_3" time="0.484" classname="Public.TestAPI"/>
  <testcase name="postsmartlistfavorite_v_3" time="0.415" classname="Private.SmartlistControllerV3"/>
  <testcase name="getServicesByLocation_v_2" time="0.414" classname="Public.ServiceLocationv2"/>
  <testcase name="postPaymentv3" time="0.418" classname="Public.PaymentExtensionV3">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at Public.PaymentExtensionV3.postPaymentv3(PaymentExtensionV3.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- postPaymentv3 -->
  <testcase name="paymentExtensionv3" time="0.468" classname="Public.PaymentExtensionV3"/>
  <testcase name="getAccountBalancesV2" time="0.51" classname="Public.GetAccountBalances"/>
  <testcase name="getAccountBalancesV24" time="0.414" classname="Public.GetAccountBalances"/>
  <testcase name="getAccountBalancesPortalv2_4" time="0.472" classname="Public.GetAccountBalances"/>
  <testcase name="TC003_1_getCashin" time="0.417" classname="Public.CashieringGet"/>
  <testcase name="TC003_getCashin" time="0.53" classname="Public.CashieringGet"/>
  <testcase name="TC004_balances" time="0.547" classname="Public.CashieringGet"/>
  <testcase name="TC003_getnextReceipt" time="0.462" classname="Public.CashieringGet"/>
  <testcase name="TC004_getReceipt" time="0.528" classname="Public.CashieringGet"/>
  <testcase name="TC005_getRegisterInfo" time="0.545" classname="Public.CashieringGet"/>
  <testcase name="TC006_gettransactions" time="0.565" classname="Public.CashieringGet"/>
  <testcase name="TC007_getAutoApply" time="0.833" classname="Public.CashieringGet"/>
  <testcase name="getCustomerDetail_v_2" time="0.444" classname="Public.customerController_v2"/>
  <testcase name="getCustomerbylocation_v_2" time="0.674" classname="Public.customerController_v2"/>
  <testcase name="getCustomerBillingOptions_v2" time="0.356" classname="Public.customerController_v2"/>
  <testcase name="getCollectionsoptions_v2" time="0.373" classname="Public.customerController_v2"/>
  <testcase name="getOtheroptions_v2" time="0.41" classname="Public.customerController_v2"/>
  <testcase name="getinfolabels_v2" time="0.381" classname="Public.customerController_v2"/>
  <testcase name="getLocationsByCustomer_v2" time="0.45" classname="Public.customerController_v2"/>
  <testcase name="getnextCustomerId_v2" time="0.391" classname="Public.customerController_v2"/>
  <testcase name="getCustomerDetail_v2" time="0.428" classname="Public.customerController_v2"/>
  <testcase name="getpreauthorizepaymentplan_v2" time="0.437" classname="Public.customerController_v2"/>
  <testcase name="putcustomersaddressv2" time="0.6" classname="Public.customerController_v2"/>
  <testcase name="putcustomerbillingoptionv2" time="0.459" classname="Public.customerController_v2"/>
  <testcase name="putcustomerscollectionsOptionsv2" time="0.614" classname="Public.customerController_v2"/>
  <testcase name="putcustomersotherOptionsv2" time="0.421" classname="Public.customerController_v2"/>
  <testcase name="putcustomersrolldownAddressCodev2" time="0.654" classname="Public.customerController_v2"/>
  <testcase name="postPaymentv2" time="0.409" classname="Public.PaymentExtension">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at Public.PaymentExtension.postPaymentv2(PaymentExtension.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- postPaymentv2 -->
  <testcase name="paymentExtensionv2" time="0.403" classname="Public.PaymentExtension"/>
  <testcase name="postPaymentv2_2" time="0.379" classname="Public.PaymentExtension"/>
  <testcase name="getAccountBalancesV3" time="0.433" classname="Public.GetAccountBalancesV3"/>
  <testcase name="getAccountBalancesPortalv3" time="0.425" classname="Public.GetAccountBalancesV3"/>
  <testcase name="getAccountBalancesPortalv3Paymentatwork" time="0.526" classname="Public.GetAccountBalancesV3">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Response body doesn&amp;apos;t match expectation.
Expected: &amp;quot;[{\&amp;quot;PastDue\&amp;quot;:\&amp;quot;0.00\&amp;quot;,\&amp;quot;CurrentBalance\&amp;quot;:\&amp;quot;350.71\&amp;quot;,\&amp;quot;UnpostedBalance\&amp;quot;:\&amp;quot;-272.97\&amp;quot;,\&amp;quot;AmountDue\&amp;quot;:\&amp;quot;77.74\&amp;quot;,\&amp;quot;AccountBalance\&amp;quot;:\&amp;quot;547.41\&amp;quot;,\&amp;quot;OverShort\&amp;quot;:\&amp;quot;469.67\&amp;quot;,\&amp;quot;DepositAmount\&amp;quot;:\&amp;quot;165.00\&amp;quot;,\&amp;quot;DepositOutstandingAmount\&amp;quot;:\&amp;quot;0.00\&amp;quot;,\&amp;quot;InstallmentBudget\&amp;quot;:\&amp;quot;0.00\&amp;quot;,\&amp;quot;InstallmentSPA\&amp;quot;:\&amp;quot;0.00\&amp;quot;,\&amp;quot;LastPaymentDate\&amp;quot;:\&amp;quot;2000-04-15\&amp;quot;,\&amp;quot;LastDueDate\&amp;quot;:\&amp;quot;2019-10-05\&amp;quot;}]&amp;quot;
  Actual: [{&amp;quot;PastDue&amp;quot;:&amp;quot;0.00&amp;quot;,&amp;quot;CurrentBalance&amp;quot;:&amp;quot;350.71&amp;quot;,&amp;quot;UnpostedBalance&amp;quot;:&amp;quot;-454.95&amp;quot;,&amp;quot;AmountDue&amp;quot;:&amp;quot;-104.24&amp;quot;,&amp;quot;AccountBalance&amp;quot;:&amp;quot;365.43&amp;quot;,&amp;quot;OverShort&amp;quot;:&amp;quot;469.67&amp;quot;,&amp;quot;DepositAmount&amp;quot;:&amp;quot;165.00&amp;quot;,&amp;quot;DepositOutstandingAmount&amp;quot;:&amp;quot;0.00&amp;quot;,&amp;quot;InstallmentBudget&amp;quot;:&amp;quot;0.00&amp;quot;,&amp;quot;InstallmentSPA&amp;quot;:&amp;quot;0.00&amp;quot;,&amp;quot;LastPaymentDate&amp;quot;:&amp;quot;2000-04-15&amp;quot;,&amp;quot;LastDueDate&amp;quot;:&amp;quot;2019-10-05&amp;quot;}]
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Response body doesn't match expectation.
Expected: "[{\"PastDue\":\"0.00\",\"CurrentBalance\":\"350.71\",\"UnpostedBalance\":\"-272.97\",\"AmountDue\":\"77.74\",\"AccountBalance\":\"547.41\",\"OverShort\":\"469.67\",\"DepositAmount\":\"165.00\",\"DepositOutstandingAmount\":\"0.00\",\"InstallmentBudget\":\"0.00\",\"InstallmentSPA\":\"0.00\",\"LastPaymentDate\":\"2000-04-15\",\"LastDueDate\":\"2019-10-05\"}]"
  Actual: [{"PastDue":"0.00","CurrentBalance":"350.71","UnpostedBalance":"-454.95","AmountDue":"-104.24","AccountBalance":"365.43","OverShort":"469.67","DepositAmount":"165.00","DepositOutstandingAmount":"0.00","InstallmentBudget":"0.00","InstallmentSPA":"0.00","LastPaymentDate":"2000-04-15","LastDueDate":"2019-10-05"}]

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:493)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:674)
at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:98)
at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:238)
at io.restassured.internal.ValidatableResponseImpl.super$2$body(ValidatableResponseImpl.groovy)
at sun.reflect.GeneratedMethodAccessor209.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy:293)
at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy)
at com.NexustAPIAutomation.java.CommonMethods.getMethod(CommonMethods.java:409)
at Public.GetAccountBalancesV3.getAccountBalancesPortalv3Paymentatwork(GetAccountBalancesV3.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getAccountBalancesPortalv3Paymentatwork -->
  <testcase name="cancelSPA_v_2" time="0.505" classname="Public.createandcancelSpa"/>
  <testcase name="createSPA_v_2" time="0.456" classname="Public.createandcancelSpa"/>
  <testcase name="putspaCalculate_v_2" time="0.409" classname="Public.createandcancelSpa"/>
  <testcase name="recancelSPA_v_2" time="1.036" classname="Public.createandcancelSpa"/>
  <testcase name="getoutstandingDocuments_v_3" time="0.456" classname="Public.spaControllerV3"/>
  <testcase name="getheaderInfo_v_3" time="0.423" classname="Public.spaControllerV3"/>
  <testcase name="getspadetails_v_3" time="0.403" classname="Public.spaControllerV3"/>
  <testcase name="getspadocuments_v_3" time="0.46" classname="Public.spaControllerV3"/>
  <testcase name="putcalculatedocuments_v_3" time="0.435" classname="Public.spaControllerV3"/>
  <testcase name="getcalculatedocuments_v_3" time="0.502" classname="Public.spaControllerV3"/>
  <testcase name="getspaAccountBalances_v_3" time="0.489" classname="Public.spaControllerV3"/>
  <testcase name="postcreateServiceOrder_v3" time="1.213" classname="Public.ServiceOrderControllerV3"/>
  <testcase name="getServiceOrder_v3" time="0.405" classname="Public.ServiceOrderControllerV3"/>
  <testcase name="getServiceOrderRequestDetails_v3" time="0.471" classname="Public.ServiceOrderControllerV3"/>
  <testcase name="getServiceOrderRequestDetailsbyOptional_v3" time="0.39" classname="Public.ServiceOrderControllerV3"/>
  <testcase name="putaddMeterReading_v_3" time="0.477" classname="Public.ServiceOrderControllerV3">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Response body doesn&amp;apos;t match expectation.
Expected: a string containing &amp;quot;true&amp;quot;
  Actual: {&amp;quot;result&amp;quot;:{&amp;quot;Success&amp;quot;:false,&amp;quot;Message&amp;quot;:&amp;quot;Error: Meter reading already in work&amp;quot;}}
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "true"
  Actual: {"result":{"Success":false,"Message":"Error: Meter reading already in work"}}

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:493)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:674)
at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:98)
at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:238)
at io.restassured.internal.ValidatableResponseImpl.super$2$body(ValidatableResponseImpl.groovy)
at sun.reflect.GeneratedMethodAccessor209.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy:293)
at io.restassured.internal.ValidatableResponseImpl.body(ValidatableResponseImpl.groovy)
at Public.ServiceOrderControllerV3.putaddMeterReading_v_3(ServiceOrderControllerV3.java:146)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- putaddMeterReading_v_3 -->
  <testcase name="putupdatecomment_v_3" time="0.415" classname="Public.ServiceOrderControllerV3"/>
  <testcase name="putaddMiscCharge_v_3" time="0.761" classname="Public.ServiceOrderControllerV3"/>
  <testcase name="putTaskComplete_v_3" time="0.455" classname="Public.ServiceOrderControllerV3"/>
  <testcase name="putswitchMeter_v_3" time="0.432" classname="Public.ServiceOrderControllerV3"/>
  <testcase name="putTaskCompleteNocharge_v3" time="0.718" classname="Public.ServiceOrderControllerV3"/>
  <testcase name="postcreateServiceOrder_v2" time="0.927" classname="Public.ServiceOrderController"/>
  <testcase name="postcreateServiceOrder_v2_ERROR" time="0.934" classname="Public.ServiceOrderController"/>
  <testcase name="getServiceOrder_v2" time="0.433" classname="Public.ServiceOrderController"/>
  <testcase name="getServiceOrderRequestDetails_v2" time="0.483" classname="Public.ServiceOrderController"/>
  <testcase name="getServiceOrderRequestDetailsbyOptional_v2" time="0.445" classname="Public.ServiceOrderController"/>
  <testcase name="putaddMeterReading_v_2" time="0.4" classname="Public.ServiceOrderController"/>
  <testcase name="putupdatecomment_v_2" time="0.402" classname="Public.ServiceOrderController"/>
  <testcase name="putaddMiscCharge_v_2" time="0.702" classname="Public.ServiceOrderController"/>
  <testcase name="putTaskComplete_v_2" time="0.423" classname="Public.ServiceOrderController"/>
  <testcase name="putswitchMeter_v_2" time="0.43" classname="Public.ServiceOrderController"/>
  <testcase name="putTaskCompleteNocharge_v2_3" time="0.411" classname="Public.ServiceOrderController"/>
  <testcase name="postcreateServiceOrder_v2_3_1" time="6.451" classname="Public.ServiceOrderController"/>
  <testcase name="elascticsearchcreateindex_v_3" time="0.39" classname="Public.searchControllerV3"/>
  <testcase name="getAccounts_v_3" time="0.003" classname="Public.searchControllerV3">
    <failure type="java.lang.AssertionError" message="Bug Reported">
      <![CDATA[java.lang.AssertionError: Bug Reported
at org.testng.Assert.fail(Assert.java:99)
at Public.searchControllerV3.getAccounts_v_3(searchControllerV3.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getAccounts_v_3 -->
  <testcase name="getAccountsAdvanced_v_3" time="0.004" classname="Public.searchControllerV3">
    <failure type="java.lang.AssertionError" message="Bug Reported">
      <![CDATA[java.lang.AssertionError: Bug Reported
at org.testng.Assert.fail(Assert.java:99)
at Public.searchControllerV3.getAccountsAdvanced_v_3(searchControllerV3.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getAccountsAdvanced_v_3 -->
  <testcase name="getCustomer_v3" time="0.483" classname="Public.searchControllerV3"/>
  <testcase name="getindex_v3" time="0.429" classname="Public.searchControllerV3"/>
  <testcase name="getServicesByLocation_v_3" time="0.392" classname="Public.ServiceLocationV3"/>
  <testcase name="TC001_saveReciept" time="6.58" classname="Public.CashieringPost"/>
  <testcase name="TC002_RecieptAdjustment" time="0.426" classname="Public.CashieringPost"/>
  <testcase name="getCustomerDetail_v_2" time="0.393" classname="Public.customerControllerV3"/>
  <testcase name="getCustomerbylocation_v_2" time="0.367" classname="Public.customerControllerV3"/>
  <testcase name="getCustomerBillingOptions_v2" time="0.441" classname="Public.customerControllerV3"/>
  <testcase name="getCollectionsoptions_v2" time="0.401" classname="Public.customerControllerV3"/>
  <testcase name="getOtheroptions_v2" time="0.399" classname="Public.customerControllerV3"/>
  <testcase name="getinfolabels_v2" time="0.376" classname="Public.customerControllerV3"/>
  <testcase name="getlocationsByCustomerv_2_4" time="0.575" classname="Public.customerControllerV3"/>
  <testcase name="getlocationsByCustomerv_2_4_ExcludeFormer" time="0.434" classname="Public.customerControllerV3"/>
  <testcase name="getLocationsByCustomer_v3" time="0.415" classname="Public.customerControllerV3"/>
  <testcase name="getnextCustomerId_v2" time="0.476" classname="Public.customerControllerV3"/>
  <testcase name="getCustomerDetail_v3" time="0.398" classname="Public.customerControllerV3"/>
  <testcase name="getpreauthorizepaymentplan_v2" time="0.508" classname="Public.customerControllerV3"/>
  <testcase name="putcustomersaddressv2" time="0.601" classname="Public.customerControllerV3"/>
  <testcase name="putcustomerbillingoptionv2" time="0.444" classname="Public.customerControllerV3"/>
  <testcase name="putcustomerscollectionsOptionsv2" time="0.439" classname="Public.customerControllerV3"/>
  <testcase name="putcustomersotherOptionsv2" time="0.396" classname="Public.customerControllerV3"/>
  <testcase name="putcustomersrolldownAddressCodev2" time="0.461" classname="Public.customerControllerV3"/>
  <testcase name="getoutstandingDocuments_v_2" time="0.39" classname="Public.spaController"/>
  <testcase name="getheaderInfo_v_2" time="0.342" classname="Public.spaController"/>
  <testcase name="getspadetails_v_2" time="0.34" classname="Public.spaController"/>
  <testcase name="getspadocuments_v_2" time="0.37" classname="Public.spaController"/>
  <testcase name="putcalculatedocuments_v_2" time="0.357" classname="Public.spaController"/>
  <testcase name="getcalculatedocuments_v_2" time="0.364" classname="Public.spaController"/>
  <testcase name="getspaAccountBalances_v_2" time="0.36" classname="Public.spaController"/>
  <testcase name="cancelSPA_v_2" time="0.54" classname="Public.createandcancelSpaV3"/>
  <testcase name="createSPA_v_2" time="0.39" classname="Public.createandcancelSpaV3"/>
  <testcase name="putspaCalculate_v_2" time="0.357" classname="Public.createandcancelSpaV3"/>
  <testcase name="recancelSPA_v_2" time="0.793" classname="Public.createandcancelSpaV3"/>
  <testcase name="getTransactions_v_2" time="0.484" classname="Private.transactionsController"/>
</testsuite> <!-- Default test -->
