<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RND-BASE-A" ignored="0" name="Default test" tests="17" failures="1" timestamp="20 Jul 2022 11:37:10 GMT" time="26.812" errors="0">
  <testcase name="elascticsearchcreateindex_v_2" time="5.779" classname="Public.searchController"/>
  <testcase name="getAccountsAdvanced_v_2" time="1.276" classname="Public.searchController"/>
  <testcase name="getAccounts_v_2" time="1.23" classname="Public.searchController"/>
  <testcase name="getCustomer_v2" time="0.5" classname="Public.searchController"/>
  <testcase name="getindex_v2" time="0.529" classname="Public.searchController"/>
  <testcase name="getconsumptionHistoryController" time="0.571" classname="Public.consumptionHistoryController"/>
  <testcase name="TC001_saveReciept" time="9.157" classname="Public.CashieringPost"/>
  <testcase name="getServicesByLocation_v_2" time="0.533" classname="Public.ServiceLocation"/>
  <testcase name="getAccountBalancesV2" time="0.632" classname="Public.GetAccountBalances"/>
  <testcase name="getCustomerDetail_v_2" time="0.45" classname="Public.customerController"/>
  <testcase name="postcreateServiceOrder_v2" time="1.095" classname="Public.ServiceOrderController"/>
  <testcase name="TC003_getCashin" time="0.494" classname="Public.CashieringGet"/>
  <testcase name="getoutstandingDocuments_v_2" time="0.465" classname="Public.spaController"/>
  <testcase name="postPaymentv2" time="0.842" classname="Public.PaymentExtension">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at Public.PaymentExtension.postPaymentv2(PaymentExtension.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- postPaymentv2 -->
  <testcase name="cancelSPA_v_2" time="0.644" classname="Public.createandcancelSpa"/>
  <testcase name="getTransactions_v_2" time="1.364" classname="Private.transactionsController"/>
  <testcase name="TC002_RecieptAdjustment" time="0.611" classname="Public.CashieringPost"/>
</testsuite> <!-- Default test -->
